package ntstatus

import "testing"

func TestCodeString(t *testing.T) {
	if got := STATUS_ACCOUNT_DISABLED.String(); got != "STATUS_ACCOUNT_DISABLED" {
		t.Fatalf("known status string = %q", got)
	}
	if got := Code(0xDEADBEEF).String(); got != "NTSTATUS(0xDEADBEEF)" {
		t.Fatalf("unknown status string = %q", got)
	}
}

func TestAllKnownCodeStrings(t *testing.T) {
	codes := map[Code]string{
		STATUS_NO_LOGON_SERVERS: "STATUS_NO_LOGON_SERVERS", STATUS_LOGON_FAILURE: "STATUS_LOGON_FAILURE",
		STATUS_ACCOUNT_RESTRICTION: "STATUS_ACCOUNT_RESTRICTION", STATUS_INVALID_LOGON_HOURS: "STATUS_INVALID_LOGON_HOURS",
		STATUS_INVALID_WORKSTATION: "STATUS_INVALID_WORKSTATION", STATUS_PASSWORD_EXPIRED: "STATUS_PASSWORD_EXPIRED",
		STATUS_ACCOUNT_DISABLED: "STATUS_ACCOUNT_DISABLED", STATUS_NOT_SUPPORTED: "STATUS_NOT_SUPPORTED",
		STATUS_TIME_DIFFERENCE_AT_DC: "STATUS_TIME_DIFFERENCE_AT_DC", STATUS_LOGON_TYPE_NOT_GRANTED: "STATUS_LOGON_TYPE_NOT_GRANTED",
		STATUS_ACCOUNT_EXPIRED: "STATUS_ACCOUNT_EXPIRED", STATUS_NOT_FOUND: "STATUS_NOT_FOUND",
		STATUS_PASSWORD_MUST_CHANGE: "STATUS_PASSWORD_MUST_CHANGE", STATUS_ACCOUNT_LOCKED_OUT: "STATUS_ACCOUNT_LOCKED_OUT",
		STATUS_NO_MATCH: "STATUS_NO_MATCH", STATUS_UNSUPPORTED_PREAUTH: "STATUS_UNSUPPORTED_PREAUTH",
	}
	for code, want := range codes {
		if got := code.String(); got != want {
			t.Fatalf("%08X.String() = %q, want %q", uint32(code), got, want)
		}
	}
}
