// Package ntstatus provides Windows status codes returned in KERB-EXT-ERROR.
package ntstatus

import "fmt"

// Code is a 32-bit NTSTATUS value.
type Code uint32

const (
	STATUS_NO_LOGON_SERVERS       Code = 0xC000005E
	STATUS_LOGON_FAILURE          Code = 0xC000006D
	STATUS_ACCOUNT_RESTRICTION    Code = 0xC000006E
	STATUS_INVALID_LOGON_HOURS    Code = 0xC000006F
	STATUS_INVALID_WORKSTATION    Code = 0xC0000070
	STATUS_PASSWORD_EXPIRED       Code = 0xC0000071
	STATUS_ACCOUNT_DISABLED       Code = 0xC0000072
	STATUS_NOT_SUPPORTED          Code = 0xC00000BB
	STATUS_TIME_DIFFERENCE_AT_DC  Code = 0xC0000133
	STATUS_LOGON_TYPE_NOT_GRANTED Code = 0xC000015B
	STATUS_ACCOUNT_EXPIRED        Code = 0xC0000193
	STATUS_PASSWORD_MUST_CHANGE   Code = 0xC0000224
	STATUS_ACCOUNT_LOCKED_OUT     Code = 0xC0000234
	STATUS_UNSUPPORTED_PREAUTH    Code = 0xC0000351
)

func (c Code) String() string {
	switch c {
	case STATUS_NO_LOGON_SERVERS:
		return "STATUS_NO_LOGON_SERVERS"
	case STATUS_LOGON_FAILURE:
		return "STATUS_LOGON_FAILURE"
	case STATUS_ACCOUNT_RESTRICTION:
		return "STATUS_ACCOUNT_RESTRICTION"
	case STATUS_INVALID_LOGON_HOURS:
		return "STATUS_INVALID_LOGON_HOURS"
	case STATUS_INVALID_WORKSTATION:
		return "STATUS_INVALID_WORKSTATION"
	case STATUS_PASSWORD_EXPIRED:
		return "STATUS_PASSWORD_EXPIRED"
	case STATUS_ACCOUNT_DISABLED:
		return "STATUS_ACCOUNT_DISABLED"
	case STATUS_NOT_SUPPORTED:
		return "STATUS_NOT_SUPPORTED"
	case STATUS_TIME_DIFFERENCE_AT_DC:
		return "STATUS_TIME_DIFFERENCE_AT_DC"
	case STATUS_LOGON_TYPE_NOT_GRANTED:
		return "STATUS_LOGON_TYPE_NOT_GRANTED"
	case STATUS_ACCOUNT_EXPIRED:
		return "STATUS_ACCOUNT_EXPIRED"
	case STATUS_PASSWORD_MUST_CHANGE:
		return "STATUS_PASSWORD_MUST_CHANGE"
	case STATUS_ACCOUNT_LOCKED_OUT:
		return "STATUS_ACCOUNT_LOCKED_OUT"
	case STATUS_UNSUPPORTED_PREAUTH:
		return "STATUS_UNSUPPORTED_PREAUTH"
	default:
		return fmt.Sprintf("NTSTATUS(0x%08X)", uint32(c))
	}
}
